modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"

[[mods]] #mandatory
modId="cardcraft" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
credits="RedRoseWarrior for porting to 1.16.5 and 1.20.1" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies.cardcraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.cardcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"